"""
FMD2 Python - HTTP Client Module
Wraps requests.Session with advanced features for manga downloading
"""

import gzip
import brotli
import zstandard as zstd
import time
import random
from typing import Optional, Dict, List, Any, Union
from pathlib import Path
from urllib.parse import urlparse, urljoin

import requests
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


from http.cookiejar import CookieJar, LWPCookieJar


class CookieManager:
    """
    Manages cookies in Netscape format compatible with FMD2
    """
    
    def __init__(self, cookie_file: Optional[Path] = None):
        self.cookie_file = cookie_file
        self.cookies = CookieJar()
        
        # Load existing cookies
        if self.cookie_file and self.cookie_file.exists():
            self.load_cookies()
    
    def load_cookies(self):
        """Load cookies from Netscape format file"""
        if not self.cookie_file or not self.cookie_file.exists():
            return
        
        try:
            with open(self.cookie_file, 'r', encoding='utf-8') as f:
                for line in f:
                    line = line.strip()
                    if not line or line.startswith('#'):
                        continue
                    
                    parts = line.split('\t')
                    if len(parts) >= 7:
                        domain = parts[0]
                        flag = parts[1]
                        path = parts[2]
                        secure = parts[3].lower() == 'true'
                        expiry = int(parts[4]) if parts[4].isdigit() else None
                        name = parts[5]
                        value = parts[6]
                        
                        # Set cookie
                        self.cookies.set(
                            name=name,
                            value=value,
                            domain=domain,
                            path=path,
                            secure=secure
                        )
        except Exception as e:
            print(f"Error loading cookies: {e}")
    
    def save_cookies(self):
        """Save cookies to Netscape format file"""
        if not self.cookie_file:
            return
        
        try:
            with open(self.cookie_file, 'w', encoding='utf-8') as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# This file was generated by FMD2 Python\n\n")
                
                for cookie in self.cookies:
                    domain = cookie.domain
                    flag = 'TRUE' if cookie.domain_specified else 'FALSE'
                    path = cookie.path
                    secure = 'TRUE' if cookie.secure else 'FALSE'
                    expiry = str(cookie.expires) if cookie.expires else '0'
                    name = cookie.name
                    value = cookie.value
                    
                    f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}\n")
        except Exception as e:
            print(f"Error saving cookies: {e}")
    
    def clear_cookies(self):
        """Clear all cookies"""
        self.cookies.clear()
    
    def get_cookies_for_domain(self, domain: str) -> Dict[str, str]:
        """Get cookies for a specific domain"""
        result = {}
        for cookie in self.cookies:
            if domain in cookie.domain:
                result[cookie.name] = cookie.value
        return result
    
    def set_cookie(self, name: str, value: str, domain: str, path: str = '/', 
                   secure: bool = False, expires: int = None):
        """Set a cookie"""
        self.cookies.set(name=name, value=value, domain=domain, path=path, secure=secure)
        self.save_cookies()


class HTTPClient:
    """
    Advanced HTTP client for manga downloading
    Features:
    - Automatic cookie management
    - GZIP, Brotli, Zstd compression support
    - Retry logic with exponential backoff
    - User-Agent rotation
    - Session persistence
    """
    
    # Common user agents for rotation
    USER_AGENTS = [
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0',
        'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Mozilla/5.0 (iPhone; CPU iPhone OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1',
        'Mozilla/5.0 (iPad; CPU OS 17_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.2 Mobile/15E148 Safari/604.1',
    ]
    
    def __init__(self, cookie_manager: Optional[CookieManager] = None, 
                 timeout: int = 30, max_retries: int = 3):
        self.cookie_manager = cookie_manager or CookieManager()
        self.timeout = timeout
        self.max_retries = max_retries
        self.current_user_agent = random.choice(self.USER_AGENTS)
        
        # Create session with retry strategy
        self.session = requests.Session()
        self.session.cookies = self.cookie_manager.cookies
        
        # Configure retry strategy
        retry_strategy = Retry(
            total=max_retries,
            backoff_factor=1.0,
            status_forcelist=[429, 500, 502, 503, 504],
            allowed_methods=["HEAD", "GET", "OPTIONS", "POST"]
        )
        
        adapter = HTTPAdapter(max_retries=retry_strategy)
        self.session.mount("http://", adapter)
        self.session.mount("https://", adapter)
        
        # Default headers
        self.default_headers = {
            'User-Agent': self.current_user_agent,
            'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
            'Accept-Language': 'en-US,en;q=0.5',
            'Accept-Encoding': 'gzip, deflate, br, zstd',
            'Connection': 'keep-alive',
            'Upgrade-Insecure-Requests': '1',
            'Cache-Control': 'max-age=0',
        }
    
    def rotate_user_agent(self):
        """Rotate to a random user agent"""
        self.current_user_agent = random.choice(self.USER_AGENTS)
        self.default_headers['User-Agent'] = self.current_user_agent
    
    def create_lua_wrapper(self) -> Dict[str, Any]:
        """Create a Lua-compatible wrapper for HTTP operations"""
        return {
            'get': self.lua_get,
            'post': self.lua_post,
            'download': self.lua_download,
        }
    
    def lua_get(self, url: str, headers: Dict = None) -> Dict[str, Any]:
        """Lua wrapper for GET request"""
        try:
            response = self.get(url, headers=headers)
            return {
                'success': True,
                'status': response.status_code,
                'body': response.text,
                'headers': dict(response.headers),
            }
        except Exception as e:
            return {
                'success': False,
                'error': str(e),
            }
    
    def lua_post(self, url: str, data: Dict = None, headers: Dict = None) -> Dict[str, Any]:
        """Lua wrapper for POST request"""
        try:
            response = self.post(url, data=data, headers=headers)
            return {
                'success': True,
                'status': response.status_code,
                'body': response.text,
                'headers': dict(response.headers),
            }
        except Exception as e:
            return {
                'success': False,
                'error': str(e),
            }
    
    def lua_download(self, url: str, filepath: str, headers: Dict = None) -> Dict[str, Any]:
        """Lua wrapper for file download"""
        try:
            self.download_file(url, filepath, headers=headers)
            return {
                'success': True,
                'filepath': filepath,
            }
        except Exception as e:
            return {
                'success': False,
                'error': str(e),
            }
    
    def get(self, url: str, headers: Dict = None, params: Dict = None,
            allow_redirects: bool = True, timeout: int = None) -> requests.Response:
        """HTTP GET request"""
        req_headers = self.default_headers.copy()
        if headers:
            req_headers.update(headers)
        
        response = self.session.get(
            url,
            headers=req_headers,
            params=params,
            allow_redirects=allow_redirects,
            timeout=timeout or self.timeout
        )
        
        # Decompress if needed
        response = self._decompress_response(response)
        
        return response
    
    def post(self, url: str, data: Dict = None, json_data: Dict = None,
             headers: Dict = None, params: Dict = None,
             allow_redirects: bool = True, timeout: int = None) -> requests.Response:
        """HTTP POST request"""
        req_headers = self.default_headers.copy()
        if headers:
            req_headers.update(headers)
        
        response = self.session.post(
            url,
            data=data,
            json=json_data,
            headers=req_headers,
            params=params,
            allow_redirects=allow_redirects,
            timeout=timeout or self.timeout
        )
        
        # Decompress if needed
        response = self._decompress_response(response)
        
        return response
    
    def download_file(self, url: str, filepath: Union[str, Path],
                      headers: Dict = None, chunk_size: int = 8192) -> str:
        """Download file to disk"""
        filepath = Path(filepath)
        filepath.parent.mkdir(parents=True, exist_ok=True)
        
        req_headers = self.default_headers.copy()
        if headers:
            req_headers.update(headers)
        
        with self.session.get(url, headers=req_headers, stream=True) as response:
            response.raise_for_status()
            
            with open(filepath, 'wb') as f:
                for chunk in response.iter_content(chunk_size=chunk_size):
                    if chunk:
                        f.write(chunk)
        
        return str(filepath)
    
    def _decompress_response(self, response: requests.Response) -> requests.Response:
        """Decompress response based on Content-Encoding"""
        encoding = response.headers.get('Content-Encoding', '').lower()
        
        if encoding == 'gzip':
            response._content = gzip.decompress(response.content)
        elif encoding == 'br':
            response._content = brotli.decompress(response.content)
        elif encoding == 'zstd':
            response._content = zstd.decompress(response.content)
        
        return response
    
    def head(self, url: str, headers: Dict = None, timeout: int = None) -> requests.Response:
        """HTTP HEAD request"""
        req_headers = self.default_headers.copy()
        if headers:
            req_headers.update(headers)
        
        return self.session.head(
            url,
            headers=req_headers,
            timeout=timeout or self.timeout
        )
    
    def resolve_url(self, base_url: str, relative_url: str) -> str:
        """Resolve relative URL against base URL"""
        return urljoin(base_url, relative_url)
    
    def extract_domain(self, url: str) -> str:
        """Extract domain from URL"""
        parsed = urlparse(url)
        return parsed.netloc
    
    def set_proxy(self, proxy_url: str):
        """Set proxy for requests"""
        proxies = {
            'http': proxy_url,
            'https': proxy_url,
        }
        self.session.proxies.update(proxies)
    
    def clear_proxy(self):
        """Clear proxy settings"""
        self.session.proxies.clear()
    
    def add_header(self, name: str, value: str):
        """Add default header"""
        self.default_headers[name] = value
    
    def remove_header(self, name: str):
        """Remove default header"""
        if name in self.default_headers:
            del self.default_headers[name]
    
    def close(self):
        """Close the session"""
        self.session.close()
        if self.cookie_manager:
            self.cookie_manager.save_cookies()
